name: APK-K Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone Project
        run: git clone -b main --depth=1 https://github.com/kensonmiao/CatVodTVOSC.git
      - name: DIY
        run: |
          chmod +x diy-K.sh
          bash ${{ github.workspace }}/diy-K.sh
      - name: Checkout Source Code and Zip
        if: ${{ env.commit }}
        run: |
          git clone ${{ env.upStream }} TVBoxOSC
          cd TVBoxOSC
          git checkout ${{ env.commit }}
          echo "tag=$(git log --date=format:'%Y%m%d-%H%M' --pretty=format:%cd ${{ env.commitS }} -1)" >> $GITHUB_ENV
          zip -q -x ".git/*" -r ${{ env.commitS }}-source.zip .
      - name: Build With Gradle
        run: |
          num=$(find ${{ github.workspace }} -name gradlew  | awk -F"/" '{print NF-1}')
          DIR=$(find ${{ github.workspace }} -name gradlew  | cut -d \/ -f$num)
          cd $DIR
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
