name: Frank self+py Build-From J Ver.

on:
  schedule:
    - cron: 0 9,15,22 * * ? 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      local_xwalk: ${{ secrets.LOCAL_XWALK }}
      # 登录蓝奏云后在控制台运行document.cookie
      ylogin: ${{ secrets.YLOGIN }}
      phpdisk_info: ${{ secrets.PHPDISK_INFO }}
      # 蓝奏云里的文件夹ID（TVBoxOS:5848262）
      lanzou_folder_id: 5889934
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone Project
        run: git clone -b main --depth=1 https://github.com/q215613905/TVBoxOS.git
      - name: DIY
        run: |
          chmod +x diy-JFrank.sh
          bash ${{ github.workspace }}/diy-JFrank.sh
      - name: Build With Gradle
        run: |
          num=$(find ${{ github.workspace }} -name gradlew  | awk -F"/" '{print NF-1}')
          DIR=$(find ${{ github.workspace }} -name gradlew  | cut -d \/ -f$num)
          cd $DIR
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.Frank.py
          path: ${{ github.workspace }}/apk/*

          
